# =====================================================
# 243-557 Labo 5 — .gitignore (repo root)
# Covers: STM32CubeIDE projects, Python / PyQt / MQTT,
# editors, and OS junk
# =====================================================

# ---------- STM32CubeIDE ----------
# Build output folders (regenerated by the IDE)
**/Debug/
**/Release/

# Compiled files / build artifacts
*.o
*.d
*.elf
*.bin
*.hex
*.map
*.list
*.su
*.cyclo
*.srec
*.lst
*.a

# Workspace data and per-user IDE settings
.metadata/
**/.settings/
RemoteSystemsTempFiles/
*.launch

# Backup files written by CubeMX / CubeIDE
*.ioc.bak
*~
*.bak

# NOTE: do NOT ignore these, teammates need them:
#   .project  .cproject  *.ioc  Core/  Drivers/  *.ld

# ---------- Python (Raspberry Pi + PC) ----------
__pycache__/
*.py[cod]
*.pyo

# Virtual environments
.venv/
venv/
env/

# Packaging / tooling caches
*.egg-info/
.pytest_cache/
.mypy_cache/

# Secrets: broker address / credentials, never commit these
.env
*.env
secrets.py
config_local.py

# ---------- Logs / captures ----------
*.log
*.pcap
*.pcapng

# ---------- Editors ----------
.vscode/
.idea/
*.swp
*.swo

# ---------- OS junk ----------
.DS_Store
Thumbs.db
desktop.ini
